FROM ghcr.io/foundry-rs/foundry:nightly-550c548a7aa94a45c1f448071307108867848429

WORKDIR /paraspace

COPY . /paraspace

RUN apk add --no-cache make

# https://docs.docker.com/config/containers/multi-service_container/
RUN echo -e '#!/bin/sh\nmake anvil' > .entrypoint.sh
RUN chmod +x .entrypoint.sh

ENTRYPOINT ["/paraspace/.entrypoint.sh"]
