[profile.default]
ffi                 = true
fs_permissions      = [{ access = "read", path = "./" }]
ignored_error_codes = [2072, 2059, 5574, 2519, 1878, 5667, 2018, 3445]
libs                = ["node_modules", "lib"]
out                 = 'out'
remappings          = ["contracts/=contracts/"]
src                 = 'contracts/'
test                = 'test'
solc_version        = '0.8.21'