#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

contracts=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.sol$") || true)

if [ ! -z "${contracts}" ]; then
  make format
  git add $(echo "$contracts" | paste -s -d " " -)
  typos \
    && yarn build \
    && yarn lint
fi
